### ISSUE TITLE
Text Label Corrupted Data?

### ISSUE THREAD

**Issue by Voidheart** [jordanbtucker/ff7r-data-editor#1] opened 2022-01-09 23:07 UTC
File: BattleCharSpec.uasset
![image](https://user-images.githubusercontent.com/29001765/148704744-780af0bf-65d2-4be6-a791-39c21d7a2bf0.png)

![image](https://user-images.githubusercontent.com/29001765/148704893-c14247f2-7ae5-44b7-9206-ff84cd4e0663.png)
Not sure if this affects data when its written but I thought I would point it out

**Comment by jordanbtucker** [comment] 2022-01-10 01:25
Thanks for reporting. This is fixed in ed45e8abf350e41d10279cb6c634ceb1d926e739. I will release a new version with this fix soon.

**Closed by jordanbtucker** 2022-01-10 01:25 UTC
Labels: bug

**Comment by jordanbtucker** [comment] 2022-01-10 01:27
Oh, and to answer your question about affecting the files, it doesn't. Those values are read-only, and only the corresponding IDs are written to the file.

It was caused by my printing the data to the console and saving that to a file instead of just saving the file directly.

**Comment by jordanbtucker** [comment] 2022-01-10 01:36
The fix has been release in https://github.com/jordanbtucker/ff7r-data-editor/releases/tag/v1.0.0-b.5.
